### Register User
POST http://localhost:3001/api/users/register
Content-Type: application/json

{
  "username": "testuser13",
  "email": "testuser13@example.com",
  "password": "password12345"
}

### Login User
POST http://localhost:3001/api/users/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

### List Users
GET http://localhost:3001/api/users/list

### List Products
GET http://localhost:3001/api/products

### Add to Cart
POST http://localhost:3001/api/cart
Content-Type: application/json

{
  "userId": 77,
  "productId": 2,
  "quantity": 2
}

### List Cart Items
GET http://localhost:3001/api/cart/1

### Delete from Cart
DELETE http://localhost:3001/api/cart/1/product/1
